Preprocess data
d-sbrgr/DSPRO1-power-prediction pull request #14
Opened 2024-10-13 12:44 UTC by michaelchristen

Added cleaned.csv, added new jupyter preprocess_data and preprocess functions adapted

2024-10-14 18:00 UTC, d-sbrgr requested changes

2024-10-14 18:00 UTC, d-sbrgr commented on power_prediction/preprocess_data.py
> +        project_root = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
```suggestion
        project_root = Path(__file__).parent.parent
```

2024-10-14 18:00 UTC, d-sbrgr commented on power_prediction/preprocess_data.py
>      pass
Calling `pass` is not necessary. To return None you simply "let the function run out".

2024-10-14 18:00 UTC, d-sbrgr commented on power_prediction/preprocess_data.py
> +    df_time = df.drop(df.index[85512:85525])
Seems very hard coded. Could you just return something like:

```
return df[df["NE_tot"] == pd.nan && df["Date"] > pd.to_datetime("2024-xx-xx")]
```

You would surely have to try this out!

2024-10-15 16:55 UTC, AaronFurlan approved these changes

2024-10-16 05:32 UTC, d-sbrgr approved these changes

2024-10-16 17:40 UTC, merged